/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'vulder' at '7/18/17 1:28 PM' with Gradle 2.14.1
 *
 * @author vulder, @date 7/18/17 1:28 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
